-- 코드를 입력하세요
SELECT ch.HISTORY_ID,
    CASE
        WHEN 1+DATEDIFF(ch.END_DATE, ch.START_DATE) >=7 
        AND 1+DATEDIFF(ch.END_DATE, ch.START_DATE) < 30
            THEN FLOOR((1-(SELECT cp.DISCOUNT_RATE*0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN cp
                    WHERE cp.CAR_TYPE = "트럭" AND cp.DURATION_TYPE="7일 이상"))
                       *(1+DATEDIFF(ch.END_DATE, ch.START_DATE))*cc.DAILY_FEE)
        WHEN 1+DATEDIFF(ch.END_DATE, ch.START_DATE) >=30 
        AND 1+DATEDIFF(ch.END_DATE, ch.START_DATE) < 90
            THEN FLOOR((1-(SELECT cp.DISCOUNT_RATE*0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN cp
                    WHERE cp.CAR_TYPE = "트럭" AND cp.DURATION_TYPE="30일 이상"))
                      *(1+DATEDIFF(ch.END_DATE, ch.START_DATE))*cc.DAILY_FEE)
        WHEN 1+DATEDIFF(ch.END_DATE, ch.START_DATE) >=90 
            THEN FLOOR((1-(SELECT cp.DISCOUNT_RATE*0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN cp
                    WHERE cp.CAR_TYPE = "트럭" AND cp.DURATION_TYPE="90일 이상"))
                      *(1+DATEDIFF(ch.END_DATE, ch.START_DATE))*cc.DAILY_FEE)
        ELSE (DATEDIFF(ch.END_DATE, ch.START_DATE)+1)*cc.DAILY_FEE
    END AS FEE
FROM CAR_RENTAL_COMPANY_CAR cc
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ch
    ON ch.CAR_ID = cc.CAR_ID
WHERE cc.CAR_TYPE = "트럭"
ORDER BY FEE DESC, ch.HISTORY_ID DESC;

# SELECT ch.START_DATE, ch.END_DATE, 1+DATEDIFF(ch.END_DATE, ch.START_DATE) FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY ch

# SELECT cp.DISCOUNT_RATE*0.01 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN cp
#                     WHERE cp.CAR_TYPE = "트럭" AND cp.DURATION_TYPE="7일 이상"