-- 코드를 작성해주세요

SELECT hd.DEPT_ID, hd.DEPT_NAME_EN, ROUND(AVG(SAL), 0) AS AVG_SAL FROM HR_DEPARTMENT hd
JOIN HR_EMPLOYEES he
    ON hd.DEPT_ID = he.DEPT_ID
GROUP BY hd.DEPT_ID
ORDER BY AVG_SAL DESC;
    